---
title: "Project 5"
author: "Callback Cats"
date: "2022-10-10"
output: html_document
bibliography: cats.bib
---

```{r,include=FALSE}
library(tidyverse) #always
library(ape) #for evo analysis
library(nlme) #ditto
library(MuMIn) #for AIC
library(geiger) #for eco analysis
library(knitr) #for knitting options
```
# Introduction

Thermoregulation is the ability of an organism to regulate their temperature within certain parameters. Internal thermoregulation is known as homeostasis which is a dynamic stability that plays an important role during physical exercise and periods of rest. The previous study, @hagey2017there, discusses the complexity of thermoregulation in humans, and the regulation of body temperature during physical exertion. When human subjects increase their activity from sedentary to active, there is an increase in body temperature due to an increase in metabolic heat production.

# Methods

An Arduino-based temperature recording system using the DHT11 sensor was implemented to record body temperatures of subjects over a 100 second period at two different intervals, once during the subject’s resting state and again after 5 minutes of activity (jumping jacks). The data captured for each subject was saved in a CSV file that was then loaded into R for analysis. Mean temperatures for each subject were plotted and combined into one figure for comparison of activity temperatures between subjects.

### Loading the Data

library(tidyverse)
dat.f <- list.files(pattern = "couch|active.csv")                      

### Merging the Data Sets

dat.l <- list()                                                                               #make an empty list
 
for(i in dat.f){
  met.dat<- unlist(strsplit(i,"_"))                                                  
  #split of the filename string
  who <- met.dat[1]                                                                     
  #store the first element
  activity <- gsub(".csv","",met.dat[2])                                        
  #store second element, dropping CSV with gsub()
  dat.l[[i]]<- read_csv(i)%>%
    mutate(who=who,activity=activity)                                       
  #read, then store data with additional columns of metada in list as position unique to i
}
  

### Combine the list into table

dat <- do.call(rbind,dat.l)                                                        #combine the list into table




# Results

dat%>%
  ggplot()+geom_boxplot(aes(x=activity,y=degC))+facet_grid(.~who)  
  
# Discussion

The objective of this report is to answer “Does body temperature vary in human subjects according to activity level?” Recordings from the Arduino DHT11 sensor showed the baseline of body temperature when in sedentary position. Meanwhile, when group members engaged in physical activity, body temperatures increased. This was congruent with the findings from “Human Thermoregulation and Measurement of Body Temperature in Exercise and Clinical Settings” that demonstrated increasing body temperatures from sedentary to activity due to the increasing output of metabolic heat caused by physical exertion. As noted in the article, routine engagement in physical activity inducing heat stress can aid in greater thermo- tolerance and improve overall function of the human body.


# Author Contributions

Data collection was worked on by all members of the team and all members also contributed to proofreading of data, results, and R code.
Clare Mungovan: Worked on the Introduction section.
Adam Qu: Described the methods used for this report.
Matteo Torquati: Put in all the code into Rmd file and formatted it.
Julie Vu: Worked on the discussion section.


# References

